import React from 'react';

const Grille = () => 
        <table>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
        <tr>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
            <td>kikou</td>
        </tr>
      </table>


export default Grille;